Repository kvanrooyen-inv/external-resource-verifier, pull requests merged in 2025-04, with the labels that each got.

#47 Implemented Consistent Checks for Updates to Notify Users
  src/components/NotificationSystem.js
  src/components/RefreshPrompt.js
Labels: enhancement

#48 Feature: Sharing Results via Serverless Backend
  .env
  .gitignore
  netlify.toml
  netlify/functions/get-report.js
  netlify/functions/save-report.js
  package-lock.json
  package.json
  src/App.js
  src/components/ReportPage.js
  src/components/ShareUI.js
  src/components/StandardUI.js
Labels: enhancement

#49 Bug Fix: Update refresh prompt wasn't working
  src/components/NotificationSystem.js
  src/components/RefreshPrompt.js
Labels: bug

#50 UI Refactor
  src/components/ReportPage.js
  src/components/StandardUI.js
  src/components/TabUI.js
  src/components/ui/AlertBadge.js
  src/components/ui/CopyNotification.js
  src/components/ui/EmptyState.js
  src/components/ui/ExpandableCard.js
  src/components/ui/TabButton.js
  src/components/ui/TabSelector.js
  src/components/ui/card.js
Labels: enhancement

#66 Implement New Checks
  netlify/functions/save-report.js
  src/components/Dashboard.js
  src/components/ui/GridFlexboxCard.js
  src/components/ui/MetaTagsCard.js
  src/components/ui/ResultsContainer.js
  src/components/ui/SemanticHTMLCard.js
  src/lib/analyzer.js
Labels: enhancement

#69 Fix: Improve Supabase Data Insertion Reliability with Enhanced Validation and Error Handling
  netlify/functions/save-report.js
Labels: bug

#70 Fixes #68 - Admin Dashbaord Not Updating
  netlify/functions/get-stats.js
Labels: bug

#73 Update README to include new checks
  README.md
Labels: documentation
